str = "HoAng Kiet jj Kiet"
print(str)
print(str[0])
print(str[9])
print(str[-1])
print(str[3:9])
print(str[3:-1])
print(len(str))
print(str.strip())
print(str.replace("H","J"))
print(str.split(" "))
print("hello \"ga\"")
print(str.lower())
print(str.casefold())
print(str.find("Kiet"))
print(str.index("Kiet"))
print(str.islower())